#! /bin/sh

$HOME/.config/polybar/launch.sh
$HOME/.config/bspwm/wallpaper.sh
sxhkd &
redshift &
xset r rate 200 30

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config focused_border_color "#ce9598"
bspc config border_width         1
bspc config window_gap           12
bspc config top_padding          30

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
