require("plugins")
require("general")
require("keybindings")
require("lsp")

require("plugins.luasnip")
require("plugins.cmp")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.lightline")
require("plugins.gitsigns")
require("plugins.nvim-tree")
require("plugins.null-ls")
require("plugins.indent-blankline")
require("plugins.copilot")

